import toolRegistery from "./tool.registery.js";
import readFileTool from "./tools/fileSystem/read.tool.js";
import listTool from "./tools/fileSystem/list.tool.js";
import writeFileTool from "./tools/fileSystem/write.tool.js";
import editFileTool from "./tools/fileSystem/edit.tool.js";
import createDirectoryTool from "./tools/fileSystem/create.tool.js";
import deleteTool from "./tools/fileSystem/delete.tool.js";
import moveTool from "./tools/fileSystem/move.tool.js";
import copyTool from "./tools/fileSystem/copy.tool.js";
import searchTool from "./tools/fileSystem/search.tool.js";
import infoTool from "./tools/fileSystem/info.tool.js";
import contentTool from "./tools/fileSystem/content.tool.js";
import screenShot from "./tools/desktop/screenshot.tool.js";
import openApplicationTool from "./tools/desktop/open.tool.js";
import closeApplcationTool from "./tools/desktop/close.tool.js";
import keyTool from "./tools/desktop/keyboard.tool.js";
import terminalTool from "./tools/terminal/terminal.tool.js";
import gitStatusTool from "./tools/git/status.tool.js";
import gitBranchTool from "./tools/git/branch.tool.js";
import gitCommit from "./tools/git/commit.tool.js";
import gitStage from "./tools/git/add.tool.js";
import gitPush from "./tools/git/push.tool.js";
import gitLog from "./tools/git/log.tool.js";
import gitCheckout from "./tools/git/checkout.tool.js";
import gitFetch from "./tools/git/fetch.tool.js";
import gitCreate from "./tools/git/createBranch.tool.js";
import gitDiff from "./tools/git/diff.tool.js";
import gitPull from "./tools/git/pull.tool.js";
import gitMerge from "./tools/git/merge.tool.js";
import gitStash from "./tools/git/stash.tool.js";
import gitShow from "./tools/git/show.tool.js";
import gitRemote from "./tools/git/remote.tool.js";
import gitRestore from "./tools/git/restore.tool.js";

export const registerTools = (): void => {
  toolRegistery.register(readFileTool);
  toolRegistery.register(listTool);
  toolRegistery.register(writeFileTool);
  toolRegistery.register(editFileTool);
  toolRegistery.register(createDirectoryTool);
  toolRegistery.register(deleteTool);
  toolRegistery.register(moveTool);
  toolRegistery.register(copyTool);
  toolRegistery.register(searchTool);
  toolRegistery.register(infoTool);
  toolRegistery.register(contentTool);
  toolRegistery.register(screenShot);
  toolRegistery.register(openApplicationTool);
  toolRegistery.register(closeApplcationTool);
  toolRegistery.register(keyTool);
  toolRegistery.register(terminalTool);
  toolRegistery.register(gitStatusTool);
  toolRegistery.register(gitBranchTool);
  toolRegistery.register(gitCommit);
  toolRegistery.register(gitStage);
  toolRegistery.register(gitPush);
  toolRegistery.register(gitLog);
  toolRegistery.register(gitCheckout);
  toolRegistery.register(gitFetch);
  toolRegistery.register(gitCreate);
  toolRegistery.register(gitDiff);
  toolRegistery.register(gitPull);
  toolRegistery.register(gitMerge);
  toolRegistery.register(gitStash);
  toolRegistery.register(gitShow);
  toolRegistery.register(gitRemote);
  toolRegistery.register(gitRestore);
};
